//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IServico3")]
    public interface IServico3 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico3/HelloWorld3", ReplyAction="http://tempuri.org/IServico3/HelloWorld3Response")]
        string HelloWorld3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico3/HelloWorld3", ReplyAction="http://tempuri.org/IServico3/HelloWorld3Response")]
        System.Threading.Tasks.Task<string> HelloWorld3Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServico3Channel : WSClient.ServiceReference3.IServico3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Servico3Client : System.ServiceModel.ClientBase<WSClient.ServiceReference3.IServico3>, WSClient.ServiceReference3.IServico3 {
        
        public Servico3Client() {
        }
        
        public Servico3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Servico3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servico3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servico3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld3() {
            return base.Channel.HelloWorld3();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorld3Async() {
            return base.Channel.HelloWorld3Async();
        }
    }
}
