//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Servico2Soap")]
    public interface Servico2Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorld2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        WSClient.ServiceReference2.HelloWorld2Response HelloWorld2(WSClient.ServiceReference2.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceReference2.HelloWorld2Response> HelloWorld2Async(WSClient.ServiceReference2.HelloWorld2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceReference2.HelloWorld2RequestBody Body;
        
        public HelloWorld2Request() {
        }
        
        public HelloWorld2Request(WSClient.ServiceReference2.HelloWorld2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorld2RequestBody {
        
        public HelloWorld2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld2Response", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceReference2.HelloWorld2ResponseBody Body;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(WSClient.ServiceReference2.HelloWorld2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld2Result;
        
        public HelloWorld2ResponseBody() {
        }
        
        public HelloWorld2ResponseBody(string HelloWorld2Result) {
            this.HelloWorld2Result = HelloWorld2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Servico2SoapChannel : WSClient.ServiceReference2.Servico2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Servico2SoapClient : System.ServiceModel.ClientBase<WSClient.ServiceReference2.Servico2Soap>, WSClient.ServiceReference2.Servico2Soap {
        
        public Servico2SoapClient() {
        }
        
        public Servico2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Servico2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servico2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servico2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceReference2.HelloWorld2Response WSClient.ServiceReference2.Servico2Soap.HelloWorld2(WSClient.ServiceReference2.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2() {
            WSClient.ServiceReference2.HelloWorld2Request inValue = new WSClient.ServiceReference2.HelloWorld2Request();
            inValue.Body = new WSClient.ServiceReference2.HelloWorld2RequestBody();
            WSClient.ServiceReference2.HelloWorld2Response retVal = ((WSClient.ServiceReference2.Servico2Soap)(this)).HelloWorld2(inValue);
            return retVal.Body.HelloWorld2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceReference2.HelloWorld2Response> WSClient.ServiceReference2.Servico2Soap.HelloWorld2Async(WSClient.ServiceReference2.HelloWorld2Request request) {
            return base.Channel.HelloWorld2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceReference2.HelloWorld2Response> HelloWorld2Async() {
            WSClient.ServiceReference2.HelloWorld2Request inValue = new WSClient.ServiceReference2.HelloWorld2Request();
            inValue.Body = new WSClient.ServiceReference2.HelloWorld2RequestBody();
            return ((WSClient.ServiceReference2.Servico2Soap)(this)).HelloWorld2Async(inValue);
        }
    }
}
